

import modulos.grafoChats.ObtenerNombre_ID8
import modulos.grafoChats.ObtenerTema_ID9
import modulos.grafoChats.PolciaDeCorrecciones_ID10
import modulos.grafoChats.assesments_ID11
import modulos.grafoChats.Visas_ID12
import modulos.grafoChats.Traducciones_ID13
import modulos.grafoChats.policiaTema_ID14
import modulos.grafoChats.obtenerPago_ID15
